services:
  app:
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - expo_cache:/root/.expo
    env_file:
      - .env
    ports:
      - "19000:19000"  # Metro
      - "19001:19001"  # Logs
      - "19002:19002"  # Devtools
      - "19006:19006"  # Web (expo start --web)
      - "8081:8081"    # RN debug/asset
    stdin_open: true
    tty: true
    environment:
      EXPO_DEVTOOLS_LISTEN_ADDRESS: "0.0.0.0"
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
volumes:
  node_modules:
  expo_cache: